# Generated by Django 3.2.9 on 2022-01-29 01:51

import components.crud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='trayecto',
            field=models.TextField(blank=True, choices=[('Aprobado', 'Aprobado'), ('En curso', 'En curso'), ('Reprobado', 'Reprobado')], max_length=9, verbose_name='Trayecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.TextField(blank=True, choices=[('Aprobado', 'Aprobado'), ('En curso', 'En curso'), ('Reprobado', 'Reprobado')], max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='upload',
            field=models.FileField(max_length=50, upload_to='uploads/%Y/%m/%d/', validators=[components.crud.models.file_size], verbose_name='Documento'),
        ),
    ]
