# Generated by Django 3.2.9 on 2022-01-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20220129_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='pnf',
            field=models.TextField(blank=True, choices=[('Administracion', 'Administracion'), ('Contaduria Publica', 'Contaduria Publica'), ('Turismo', 'Turismo'), ('Agroalimentacion', 'Agroalimentacion'), ('Informatica', 'Informatica'), ('Construccion Civil', 'Construccion Civil'), ('Procesamiento y Distribucion de alimentos', 'Procesamiento y Dist. de alimentos'), ('Terapia Ocupacional', 'Terapia Ocupacional'), ('Fisioterapia', 'Fisioterapia')], max_length=41, null=True, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='trayecto',
            field=models.TextField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3, verbose_name='Trayecto'),
        ),
    ]
