# Generated by Django 3.2.9 on 2021-12-02 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_proyecto_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.caso', verbose_name='Caso'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.responsable', verbose_name='Responsable'),
        ),
    ]
