# Generated by Django 3.2.9 on 2021-12-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20211202_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='upload',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
