# Generated by Django 3.2.9 on 2022-02-09 18:50

import components.crud.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('parroquia', models.CharField(max_length=200, verbose_name='Parroquia')),
                ('municipio', models.CharField(default='Tucupita', max_length=200, verbose_name='Municipio')),
                ('estado', models.CharField(default='Delta Amacuro', max_length=200, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('cedula', models.PositiveIntegerField(unique=True, verbose_name='Cédula')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('pnf', models.TextField(blank=True, choices=[('Administración', 'Administración'), ('Contaduría Pública', 'Contaduria Pública'), ('Turismo', 'Turismo'), ('Agroalimentación', 'Agroalimentación'), ('Informática', 'Informática'), ('Construcción Civil', 'Construcción Civil'), ('Procesamiento y Distribución de alimentos', 'Procesamiento y Dist. de alimentos'), ('Terapia Ocupacional', 'Terapia Ocupacional'), ('Fisioterapia', 'Fisioterapia'), ('Medicina Veterinaria', 'Medicina Veterinaria'), ('Enfermería Integral Comunitaria', 'Enfermeria Int. Comunitaria')], max_length=50, null=True, verbose_name='Carrera')),
                ('estado', models.TextField(blank=True, choices=[('Aprobado', 'Aprobado'), ('En curso', 'En curso'), ('Reprobado', 'Reprobado')], max_length=50, verbose_name='Estatus')),
                ('trayecto', models.TextField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3, verbose_name='Trayecto')),
                ('year', models.CharField(blank=True, choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], max_length=20, verbose_name='Periodo Académico')),
                ('resumen', models.TextField(default='ninguno', max_length=2000, verbose_name='Resumen')),
                ('integrantes', models.TextField(default='no disponible', max_length=300, verbose_name='Integrantes')),
                ('upload', models.FileField(blank=True, max_length=50, upload_to='uploads/%Y/%m/%d/', validators=[components.crud.models.file_size], verbose_name='Documento')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.caso', verbose_name='Caso')),
                ('responsable', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crud.responsable', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['id'],
            },
        ),
    ]
