# Generated by Django 3.2.9 on 2022-03-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_proyecto_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='linea',
            field=models.CharField(blank=True, max_length=100, verbose_name='Linea de Investigación'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='pnf',
            field=models.TextField(blank=True, choices=[('Administración', 'Administración'), ('Contaduría Pública', 'Contaduria Pública'), ('Turismo', 'Turismo'), ('Agroalimentación', 'Agroalimentación'), ('Informática', 'Informática'), ('Construcción Civil', 'Construcción Civil'), ('Procesamiento y Distribución de alimentos', 'Procesamiento y Dist. de alimentos'), ('Terapia Ocupacional', 'Terapia Ocupacional'), ('Fisioterapia', 'Fisioterapia'), ('Medicina Veterinaria', 'Medicina Veterinaria'), ('Enfermería Integral Comunitaria', 'Enfermeria Int. Comunitaria'), ('Educación Inicial', 'Educación Inicial')], max_length=50, null=True, verbose_name='Carrera'),
        ),
    ]
