# Generated by Django 3.2.9 on 2022-04-07 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20220322_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='nombre',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='Nombre'),
        ),
    ]
