# Generated by Django 3.2.9 on 2022-02-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_proyecto_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='resumen',
            field=models.TextField(default='ninguno', max_length=2000, verbose_name='Resumen'),
        ),
    ]
