# Generated by Django 3.2.9 on 2022-04-07 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20220407_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='estado',
            field=models.CharField(default='Delta Amacuro', max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Solo se permiten letras')], verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='municipio',
            field=models.CharField(default='Tucupita', max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Solo se permiten letras')], verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='nombre',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\s]*$', 'Solo se permiten caracteres alfanuméricos')], verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='parroquia',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\s]*$', 'Solo se permiten caracteres alfanuméricos')], verbose_name='Parroquia'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.TextField(blank=True, choices=[('Aprobado', 'Aprobado'), ('En curso', 'En curso'), ('Reprobado', 'Reprobado')], max_length=20, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='integrantes',
            field=models.TextField(default='no disponible', max_length=300, validators=[django.core.validators.RegexValidator('^[a-zA-Z,0-9 ]+$', 'Solo se permiten caracteres alfanuméricos y comas')], verbose_name='Integrantes'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='linea',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Solo se permiten letras')], verbose_name='Linea de Investigación'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z,0-9 ]+$', 'Solo se permiten caracteres alfanuméricos y comas')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='resumen',
            field=models.TextField(default='ninguno', max_length=2000, validators=[django.core.validators.RegexValidator('^[a-zA-Z,0-9 ]+$', 'Solo se permiten caracteres alfanuméricos y comas')], verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='year',
            field=models.CharField(blank=True, choices=[('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=5, verbose_name='Periodo Académico'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Solo se permiten letras')], verbose_name='Nombre'),
        ),
    ]
