# Generated by Django 3.2.9 on 2022-02-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20220203_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='pnf',
            field=models.TextField(blank=True, choices=[('Administracion', 'Administracion'), ('Contaduria Publica', 'Contaduria Publica'), ('Turismo', 'Turismo'), ('Agroalimentacion', 'Agroalimentacion'), ('Informatica', 'Informatica'), ('Construccion Civil', 'Construccion Civil'), ('Procesamiento y Distribucion de alimentos', 'Procesamiento y Dist. de alimentos'), ('Terapia Ocupacional', 'Terapia Ocupacional'), ('Fisioterapia', 'Fisioterapia'), ('Medicina Veterinaria', 'Medicina Veterinaria'), ('Enfermeria Integral Comunitaria', 'Enfermeria Int. Comunitaria')], max_length=255, null=True, verbose_name='Carrera'),
        ),
    ]
