# Generated by Django 3.2.9 on 2022-04-07 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20220407_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='estado',
            field=models.CharField(default='Delta Amacuro', max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]*$', 'Solo se permiten letras')], verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='municipio',
            field=models.CharField(default='Tucupita', max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]*$', 'Solo se permiten letras')], verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='nombre',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]]*$', 'Solo se permiten caracteres alfanuméricos')], verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='parroquia',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]]*$', 'Solo se permiten caracteres alfanuméricos')], verbose_name='Parroquia'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='integrantes',
            field=models.TextField(default='no disponible', max_length=300, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑáéíóúÁÉÍÓÚ,0-9 ]+$', 'Solo se permiten caracteres alfanuméricos y comas')], verbose_name='Integrantes'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='linea',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]*$', 'Solo se permiten letras')], verbose_name='Linea de Investigación'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑáéíóúÁÉÍÓÚ,0-9 ]+$', 'Solo se permiten caracteres alfanuméricos y comas')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='resumen',
            field=models.TextField(default='ninguno', max_length=2000, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑáéíóúÁÉÍÓÚ,0-9 ]+$', 'Solo se permiten caracteres alfanuméricos y comas')], verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]*$', 'Solo se permiten letras')], verbose_name='Nombre'),
        ),
    ]
