# Generated by Django 3.2.9 on 2022-02-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_alter_proyecto_pnf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='pnf',
            field=models.TextField(blank=True, choices=[('Administración', 'Administración'), ('Contaduría Pública', 'Contaduria Pública'), ('Turismo', 'Turismo'), ('Agroalimentación', 'Agroalimentación'), ('Informática', 'Informática'), ('Construcción Civil', 'Construcción Civil'), ('Procesamiento y Distribución de alimentos', 'Procesamiento y Dist. de alimentos'), ('Terapia Ocupacional', 'Terapia Ocupacional'), ('Fisioterapia', 'Fisioterapia'), ('Medicina Veterinaria', 'Medicina Veterinaria'), ('Enfermería Integral Comunitaria', 'Enfermeria Int. Comunitaria')], max_length=50, null=True, verbose_name='Carrera'),
        ),
    ]
