# Generated by Django 3.2.9 on 2022-04-07 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_auto_20220407_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='integrantes',
            field=models.TextField(default='no disponible', max_length=300, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑáéíóúÁÉÍÓÚ",0-9 ]+$', 'Solo se permiten caracteres alfanuméricos,comas y comillas (")')], verbose_name='Integrantes'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑáéíóúÁÉÍÓÚ",0-9 ]+$', 'Solo se permiten caracteres alfanuméricos,comas y comillas (")')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='resumen',
            field=models.TextField(default='ninguno', max_length=2000, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑáéíóúÁÉÍÓÚ",0-9 ]+$', 'Solo se permiten caracteres alfanuméricos,comas y comillas (")')], verbose_name='Resumen'),
        ),
    ]
