# Generated by Django 3.2.9 on 2022-04-07 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_auto_20220407_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='nombre',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZñÑáéíóúÁÉÍÓÚ"\\s]*$', 'Solo se permiten caracteres alfanuméricos y comillas (")')], verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='parroquia',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZñÑáéíóúÁÉÍÓÚ"\\s]*$', 'Solo se permiten caracteres alfanuméricos y comillas (")')], verbose_name='Parroquia'),
        ),
    ]
