# Generated by Django 3.2.9 on 2022-02-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('Administracion', 'Coord. Administración'), ('Contaduria Publica', 'Coord. Contaduria Publica'), ('Turismo', 'Coord.Turismo'), ('Agroalimentacion', 'Coord. Agroalimentación'), ('Informatica', 'Coord. Informatica'), ('Construccion Civil', 'Coord. Construcción Civil'), ('Terapia Ocupacional', 'Coord. Terapia Ocupacional'), ('Fisioterapia', 'Coord. Fisioterapia'), ('Medicina Veterinaria', 'Coord. Medicina Veterinaria'), ('Enfermeria Integral Comunitaria', 'Coord. Enfermeria Int.')], max_length=255, unique=True, verbose_name='Rol'),
        ),
    ]
