# Generated by Django 3.2.9 on 2022-02-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('Coord. Proyectos', 'Coord. Proyectos'), ('Administración', 'Coord. Administración'), ('Contaduría Pública', 'Coord. Contaduría Pública'), ('Turismo', 'Coord.Turismo'), ('Agroalimentación', 'Coord. Agroalimentación'), ('Informática', 'Coord. Informática'), ('Construcción Civil', 'Coord. Construcción Civil'), ('Procesamiento y Distribución de alimentos', 'Coord. Proc. y Dist. de alimentos'), ('Terapia Ocupacional', 'Coord. Terapia Ocupacional'), ('Fisioterapia', 'Coord. Fisioterapia'), ('Medicina Veterinaria', 'Coord. Medicina Veterinaria'), ('Enfermería Integral Comunitaria', 'Coord. Enfermeria Int.')], max_length=50, unique=True, verbose_name='Rol'),
        ),
    ]
