# Generated by Django 3.2.9 on 2022-01-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.TextField(choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('Administracion', 'Coord. Administración'), ('Contaduria Publica', 'Coord. Contaduria Publica'), ('Turismo', 'Coord.Turismo'), ('Agroalimentacion', 'Coord. Agroalimentación'), ('Informatica', 'Coord. Informatica'), ('Construccion Civil', 'Coord. Construcción Civil'), ('Procesamiento y Distribución de alimentos', 'Coord. Proc. y Dist. de alimentos'), ('Terapia Ocupacional', 'Coord. Terapia Ocupacional'), ('Fisioterapia', 'Coord. Fisioterapia')], max_length=41, unique=True, verbose_name='Rol'),
        ),
    ]
