# Generated by Django 3.2.9 on 2022-01-22 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pnf',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crud.carrera', verbose_name='Caso'),
        ),
    ]
